language:
    node_js
node_js:
    - 'node'

os:
    - linux
    - osx

install:
    - sh ./.ci/install_nvim_${TRAVIS_OS_NAME}.sh
    - npm run setup
    - npm install -g codecov
    - npm install -g neovim
    - git clone --depth 1 https://github.com/thinca/vim-themis vim-themis

env:
    global:
        - THEMIS_VIM=nvim
        - THEMIS_ARGS="-e -s --headless"
    matrix:
        - NEOVIM_VERSION_TAG=v0.3.3

script:
    - PATH="./vim-themis/bin:$HOME/neovim/bin:$PATH" THEMIS_HOME=./vim-themis make test
    - codecov

cache:
    directories:
        - "$HOME/.npm"
