environment:
    matrix:
        - nodejs_version: '10'

matrix:
    fast_finish: true

build: off
shallow_clone: true

install:
    - ps: Install-Product node $env:nodejs_version
    - npm install --global npm@latest
    - set PATH=%APPDATA%\npm;%PATH%
    - npm install -g neovim
    - npm install

    - ps: |
        $zip = $Env:APPVEYOR_BUILD_FOLDER + '\nvim.zip'
        $url = 'https://github.com/neovim/neovim/releases/download/nightly/nvim-win64.zip'
        (New-Object Net.WebClient).DownloadFile($url, $zip)
        [Reflection.Assembly]::LoadWithPartialName('System.IO.Compression.FileSystem') > $null
        [System.IO.Compression.ZipFile]::ExtractToDirectory($zip, $Env:APPVEYOR_BUILD_FOLDER)
        $Env:THEMIS_VIM = $Env:APPVEYOR_BUILD_FOLDER + '\Neovim\bin\nvim.exe'
        $Env:THEMIS_ARGS = '-e -s --headless'

    - git -c advice.detachedHead=false clone https://github.com/thinca/vim-themis --single-branch --depth 1 %TEMP%\vim-themis
    - set THEMIS_HOME=%TEMP%\vim-themis
    - set PATH=%THEMIS_HOME%\bin;%PATH%

test_script:
    - node --version
    - npm --version
    - npm run build
    - npm run test -- --testMatch="**\src\**\*.test.ts"
    - echo %PATH%
    - echo %THEMIS_HOME%
    - echo %THEMIS_VIM%
    - echo %THEMIS_ARGS%
    - '%THEMIS_VIM% --version'
    - '%THEMIS_VIM% -u update_remote_plugins.vim -i NONE -n --headless +q'
    - themis --version
    - themis

cache:
    - '%APPDATA%\npm-cache'
